// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PbException.proto

package protomodel;

public final class PbException {
  private PbException() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(protomodel.PbException.code);
    registry.add(protomodel.PbException.level);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code BallException}
   */
  public enum BallException
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>GENERAL_EXCEPTION = 0;</code>
     */
    GENERAL_EXCEPTION(0),
    /**
     * <code>ACCESS_DENIED = 1;</code>
     */
    ACCESS_DENIED(1),
    /**
     * <code>SESSION_EXPIRED = 2;</code>
     */
    SESSION_EXPIRED(2),
    /**
     * <code>MALFORMED_SESSION = 3;</code>
     */
    MALFORMED_SESSION(3),
    /**
     * <code>DUPLICATED_LOGIN = 4;</code>
     */
    DUPLICATED_LOGIN(4),
    /**
     * <code>INVALID_PARAMETER = 5;</code>
     */
    INVALID_PARAMETER(5),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>GENERAL_EXCEPTION = 0;</code>
     */
    public static final int GENERAL_EXCEPTION_VALUE = 0;
    /**
     * <code>ACCESS_DENIED = 1;</code>
     */
    public static final int ACCESS_DENIED_VALUE = 1;
    /**
     * <code>SESSION_EXPIRED = 2;</code>
     */
    public static final int SESSION_EXPIRED_VALUE = 2;
    /**
     * <code>MALFORMED_SESSION = 3;</code>
     */
    public static final int MALFORMED_SESSION_VALUE = 3;
    /**
     * <code>DUPLICATED_LOGIN = 4;</code>
     */
    public static final int DUPLICATED_LOGIN_VALUE = 4;
    /**
     * <code>INVALID_PARAMETER = 5;</code>
     */
    public static final int INVALID_PARAMETER_VALUE = 5;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BallException valueOf(int value) {
      return forNumber(value);
    }

    public static BallException forNumber(int value) {
      switch (value) {
        case 0: return GENERAL_EXCEPTION;
        case 1: return ACCESS_DENIED;
        case 2: return SESSION_EXPIRED;
        case 3: return MALFORMED_SESSION;
        case 4: return DUPLICATED_LOGIN;
        case 5: return INVALID_PARAMETER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BallException>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BallException> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BallException>() {
            public BallException findValueByNumber(int number) {
              return BallException.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return protomodel.PbException.getDescriptor().getEnumTypes().get(0);
    }

    private static final BallException[] VALUES = values();

    public static BallException valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BallException(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BallException)
  }

  public static final int CODE_FIELD_NUMBER = 50000;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.Integer> code = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Integer.class,
        null);
  public static final int LEVEL_FIELD_NUMBER = 50001;
  /**
   * <code>extend .google.protobuf.EnumValueOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumValueOptions,
      java.lang.String> level = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.String.class,
        null);

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PbException.proto\032 google/protobuf/des" +
      "criptor.proto*\361\001\n\rBallException\022%\n\021GENER" +
      "AL_EXCEPTION\020\000\032\016\200\265\030\220N\212\265\030\005ERROR\022!\n\rACCESS" +
      "_DENIED\020\001\032\016\200\265\030\221N\212\265\030\005ERROR\022\"\n\017SESSION_EXP" +
      "IRED\020\002\032\r\200\265\030\222N\212\265\030\004INFO\022%\n\021MALFORMED_SESSI" +
      "ON\020\003\032\016\200\265\030\223N\212\265\030\005ERROR\022#\n\020DUPLICATED_LOGIN" +
      "\020\004\032\r\200\265\030\224N\212\265\030\004INFO\022&\n\021INVALID_PARAMETER\020\005" +
      "\032\017\200\265\030\260\352\001\212\265\030\005DEBUG:1\n\004code\022!.google.proto" +
      "buf.EnumValueOptions\030\320\206\003 \001(\005:2\n\005level\022!." +
      "google.protobuf.EnumValueOptions\030\321\206\003 \001(\t",
      "B\031\n\nprotomodelB\013PbExceptionb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    code.internalInit(descriptor.getExtensions().get(0));
    level.internalInit(descriptor.getExtensions().get(1));
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(protomodel.PbException.code);
    registry.add(protomodel.PbException.level);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
